# Generated by Django 4.1 on 2022-09-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0002_file_uploadfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfield',
            name='author',
        ),
        migrations.RemoveField(
            model_name='uploadfield',
            name='title',
        ),
    ]
