# Generated by Django 4.1 on 2022-09-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0003_remove_uploadfield_author_remove_uploadfield_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfield',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
